### ISSUE TITLE
[MOVED] Shared notes formatting issue

### ISSUE THREAD

**Issue by pedrobmarin** [alangecker/bbb-etherpad-plugin#3]
From https://github.com/bigbluebutton/bigbluebutton/issues/7937
```
With the current implementation of Share notes, it seems like the formatting only works if I selected the text and then apply the style.

Steps to reproduce.

    Open Shared Notes
    Click "Bold"
    Start typing.

When you start typing, you'll see that the text isn't bold. I need to select the piece of writing and then click the bold button to apply the style.
```

cc @tylercopeland

**Comment by alangecker** [comment]
~~I can reproduce this within an normal etherpad instance.
shouldn't this then rather be moved to https://github.com/ether/etherpad-lite/issues? :)~~

**Comment by alangecker** [comment]
the behavior is intended by the etherpad devs: https://github.com/ether/etherpad-lite/issues/4308#issuecomment-693226947
but there is a plugin to enable it: https://github.com/ether/ep_sticky_attributes

if it is wished, this plugin could be included in bbb-docker and the ubuntu packages.

@pedrobmarin do you have any idea where a list of the plugins included in the BBB releases could be stored?
As far as I know it is currently only stored in the closed source ubuntu packaging scripts.

**Comment by pedrobmarin** [comment]
That's a great suggestion, @alangecker . I'll ask the closed source packaging maintainer for this to be considered.

**Comment by pedrobmarin** [comment]
> @pedrobmarin do you have any idea where a list of the plugins included in the BBB releases could be stored?
> As far as I know it is currently only stored in the closed source ubuntu packaging scripts.

@alangecker just remembered something that might be interesting to mention. I'm not completely aware of the details but there is an open initiative from some other community members to have a more transparent packaging process. I believe this involves @schrd and @basisbit. You guys should definitely get in touch (if aren't yet).

(sorry if I wrongly pinned anyone)

**Comment by pedrobmarin** [comment]
**ep_sticky_attributes** added to the package.
