### ISSUE TITLE
[MOVED] Explore more meaningful naming convention for exported shared notes

### ISSUE THREAD

**Issue by pedrobmarin** [alangecker/bbb-etherpad-plugin#4]
From https://github.com/bigbluebutton/bigbluebutton/issues/7936

```
Today if I downloaded a .txt version of a shared note the name of the file looks something like this a66f302a.txt.

I was wondering if it's possible to have something more meaningful like "meeting-name-mm-dd-yy-"?
```

cc @tylercopeland

**Comment by danielpetri1** [comment]
Maybe this can be closed since it now defaults to "Shared_Notes.pdf" ([PR](https://github.com/alangecker/bbb-etherpad-plugin/pull/6)). A timestamp is already present in the file's metadata and this way we don't run into timezone troubles.
